# Generated by Django 5.1.1 on 2024-09-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablero',
            old_name='nombbre',
            new_name='nombre',
        ),
    ]
