# Generated by Django 5.1.1 on 2024-09-18 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_rename_nombbre_tablero_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('orden_lista', models.IntegerField()),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Listas', to='trello.tablero')),
            ],
        ),
    ]
