# Generated by Django 5.1.1 on 2024-09-18 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_lista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50)),
                ('orden_Tarea', models.IntegerField()),
                ('archivado', models.BooleanField()),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tareas', to='trello.lista')),
            ],
        ),
    ]
